name: CD

on:
  release:
    types:
      - published

jobs:
  verify:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-ci.yaml@99c24709710a37e286adca6879d8d5faf46224fc
    permissions:
      contents: read
    with:
      ui-path: "ui"
      pnpm-version: 10
      node-version: 24
      java-version: 21

  cd:
    needs: verify
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@99c24709710a37e286adca6879d8d5faf46224fc
    secrets:
      # 发布到Halo应用商店所需的个人访问令牌
      halo-pat: ${{ secrets.HALO_PAT }}
    permissions:
      contents: write
    with:
      ui-path: "ui"
      pnpm-version: 10
      node-version: 24
      java-version: 21
      skip-appstore-release: false
      app-id: app-1dondjfv
