name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-ci.yaml@99c24709710a37e286adca6879d8d5faf46224fc
    with:
      ui-path: "ui"
      pnpm-version: 10
      node-version: 24
      java-version: 21
